name: Building recovery

on: workflow_dispatch

env:
  MANIFEST: git://github.com/SHRP/platform_manifest_twrp_omni.git -b v3_9.0
  DEVICE: I001D
  DT_LINK: git://github.com/Divkix/android_device_asus_I001D-SHRP.git -b android-9.0
  DT_PATH: device/asus/I001D
  GIT_USER: Divkix
  GIT_EMAIL: techdroidroot@gmail.com
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

       - name: Setting up build environment
         run: |
            git config --global user.name "${GIT_USER}"
            git config --global user.email "${GIT_EMAIL}"
            git config --global color.ui true
            mkdir recovery
            git clone https://github.com/akhilnarang/scripts.git
            chmod +x scripts/setup/android_build_env.sh
            cd scripts/setup
            ./android_build_env.sh
            sudo rm /usr/bin/python
            sudo ln -s /usr/bin/python2 /usr/bin/python

       - name: Syncing Recovery Source
         run: |
             cd recovery
             repo init --depth=1 -u ${MANIFEST} --groups=all,-notdefault,-device,-darwin,-x86,-mips
             repo sync -c -q --force-sync --no-clone-bundle --no-tags -j6

       - name: Syncing Device Tree
         run: |
             cd recovery
             git clone ${DT_LINK} --depth=1 ${DT_PATH}

       - name: Building Recovery
         run: |
              cd recovery
              export ALLOW_MISSING_DEPENDENCIES=true
              source build/envsetup.sh
              lunch omni_${DEVICE}-eng
              mka recoveryimage

       - uses: actions/upload-artifact@v2
         with:
          name: RecoveryZip
          path: recovery/out/target/product/*/*.zip

       - uses: actions/upload-artifact@v2
         with:
          name: RecoveryImage
          path: recovery/out/target/product/*/*.img